############# English navigation ##############

# main menu
[[main]]
name = "Inicio"
url = "/"
weight = 1

[[main]]
name = "Sobre Mi"
url = "about/"
weight = 2

[[main]]
name = "Blog"
url = "blog/"
weight = 3

# footer menu
[[footer]]
name = "Sobre Mi"
url = "about/"
weight = 1

[[footer]]
name = "Blog"
url = "blog/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "Politica-de-Privacidad/"
weight = 3
